export const TEST_GET_METHOD = 'TEST_GET_METHOD'
export const TEST_GET_SUCCESS = 'TEST_GET_SUCCESS'
export const TEST_GET_METHOD_ERR = 'TEST_GET_METHOD_ERR'

export const TICK_CLOCK = 'TICK_CLOCK'
export const START_CLOCK = 'START_CLOCK'

export const LOAD_DATASAGA = 'LOAD_DATASAGA'
export const LOAD_DATASAGA_SUCCESS = 'LOAD_DATASAGA_SUCCESS'
export const LOAD_DATASAGA_ERR = 'LOAD_DATASAGA_ERR'