export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERR = 'GET_USER_ERR'

export const TICK_CLOCK = 'TICK_CLOCK'
export const START_CLOCK = 'START_CLOCK'

export const LOAD_DATASAGA = 'LOAD_DATASAGA'
export const LOAD_DATASAGA_SUCCESS = 'LOAD_DATASAGA_SUCCESS'
export const LOAD_DATASAGA_ERR = 'LOAD_DATASAGA_ERR'

export const ADD_USER = 'ADD_USER'
export const ADD_USER_ERR = 'ADD_USER_ERR'